import 'dotenv/config';
import express from 'express';
import http from 'http';
import { WebSocketServer } from 'ws';
const app=express(), server=http.createServer(app), wss=new WebSocketServer({server});
const PORT=Number(process.env.PORT||3000), KEY=process.env.YOUTUBE_API_KEY, VIDEO=process.env.YOUTUBE_VIDEO_ID, TARGET=Math.max(1,Number(process.env.TARGET_SCORE||1000)), FALLBACK=Math.max(1000,Number(process.env.POLL_FALLBACK_MS||5000)), SUPERCHAT_POINTS=Math.max(1,Number(process.env.SUPERCHAT_POINTS||10)), SUPERSTICKER_POINTS=Math.max(1,Number(process.env.SUPERSTICKER_POINTS||10));
const countries=[
['Afghanistan','🇦🇫'],['Albania','🇦🇱'],['Algeria','🇩🇿'],['Andorra','🇦🇩'],['Angola','🇦🇴'],['Argentina','🇦🇷'],['Armenia','🇦🇲'],['Australia','🇦🇺'],['Austria','🇦🇹'],['Azerbaijan','🇦🇿'],['Bahamas','🇧🇸'],['Bahrain','🇧🇭'],['Bangladesh','🇧🇩'],['Barbados','🇧🇧'],['Belarus','🇧🇾'],['Belgium','🇧🇪'],['Belize','🇧🇿'],['Benin','🇧🇯'],['Bhutan','🇧🇹'],['Bolivia','🇧🇴'],['Botswana','🇧🇼'],['Brazil','🇧🇷'],['Brunei','🇧🇳'],['Bulgaria','🇧🇬'],['Burundi','🇧🇮'],['Cambodia','🇰🇭'],['Cameroon','🇨🇲'],['Canada','🇨🇦'],['Chad','🇹🇩'],['Chile','🇨🇱'],['China','🇨🇳'],['Colombia','🇨🇴'],['Congo','🇨🇬'],['Costa Rica','🇨🇷'],['Croatia','🇭🇷'],['Cuba','🇨🇺'],['Cyprus','🇨🇾'],['Czechia','🇨🇿'],['Denmark','🇩🇰'],['Dominican Republic','🇩🇴'],['Ecuador','🇪🇨'],['Egypt','🇪🇬'],['Estonia','🇪🇪'],['Ethiopia','🇪🇹'],['Fiji','🇫🇯'],['Finland','🇫🇮'],['France','🇫🇷'],['Gabon','🇬🇦'],['Gambia','🇬🇲'],['Georgia','🇬🇪'],['Germany','🇩🇪'],['Ghana','🇬🇭'],['Greece','🇬🇷'],['Grenada','🇬🇩'],['Guatemala','🇬🇹'],['Guinea','🇬🇳'],['Guyana','🇬🇾'],['Haiti','🇭🇹'],['Honduras','🇭🇳'],['Hungary','🇭🇺'],['Iceland','🇮🇸'],['India','🇮🇳'],['Indonesia','🇮🇩'],['Iran','🇮🇷'],['Iraq','🇮🇶'],['Ireland','🇮🇪'],['Israel','🇮🇱'],['Italy','🇮🇹'],['Jamaica','🇯🇲'],['Japan','🇯🇵'],['Jordan','🇯🇴'],['Kazakhstan','🇰🇿'],['Kenya','🇰🇪'],['Kuwait','🇰🇼'],['Kyrgyzstan','🇰🇬'],['Laos','🇱🇦'],['Latvia','🇱🇻'],['Lebanon','🇱🇧'],['Lesotho','🇱🇸'],['Liberia','🇱🇷'],['Libya','🇱🇾'],['Liechtenstein','🇱🇮'],['Lithuania','🇱🇹'],['Luxembourg','🇱🇺'],['Madagascar','🇲🇬'],['Malawi','🇲🇼'],['Malaysia','🇲🇾'],['Maldives','🇲🇻'],['Mali','🇲🇱'],['Malta','🇲🇹'],['Mauritius','🇲🇺'],['Mexico','🇲🇽'],['Moldova','🇲🇩'],['Monaco','🇲🇨'],['Mongolia','🇲🇳'],['Montenegro','🇲🇪'],['Morocco','🇲🇦'],['Mozambique','🇲🇿'],['Myanmar','🇲🇲'],['Namibia','🇳🇦'],['Nepal','🇳🇵'],['Netherlands','🇳🇱'],['New Zealand','🇳🇿'],['Nicaragua','🇳🇮'],['Niger','🇳🇪'],['Nigeria','🇳🇬'],['North Korea','🇰🇵'],['North Macedonia','🇲🇰'],['Norway','🇳🇴'],['Oman','🇴🇲'],['Pakistan','🇵🇰'],['Palau','🇵🇼'],['Palestine','🇵🇸'],['Panama','🇵🇦'],['Papua New Guinea','🇵🇬'],['Paraguay','🇵🇾'],['Peru','🇵🇪'],['Philippines','🇵🇭'],['Poland','🇵🇱'],['Portugal','🇵🇹'],['Qatar','🇶🇦'],['Romania','🇷🇴'],['Russia','🇷🇺'],['Rwanda','🇷🇼'],['Samoa','🇼🇸'],['San Marino','🇸🇲'],['Saudi Arabia','🇸🇦'],['Senegal','🇸🇳'],['Serbia','🇷🇸'],['Seychelles','🇸🇨'],['Singapore','🇸🇬'],['Slovakia','🇸🇰'],['Slovenia','🇸🇮'],['Somalia','🇸🇴'],['South Africa','🇿🇦'],['South Korea','🇰🇷'],['South Sudan','🇸🇸'],['Spain','🇪🇸'],['Sri Lanka','🇱🇰'],['Sudan','🇸🇩'],['Suriname','🇸🇷'],['Sweden','🇸🇪'],['Switzerland','🇨🇭'],['Syria','🇸🇾'],['Taiwan','🇹🇼'],['Tajikistan','🇹🇯'],['Tanzania','🇹🇿'],['Thailand','🇹🇭'],['Togo','🇹🇬'],['Tonga','🇹🇴'],['Tunisia','🇹🇳'],['Turkey','🇹🇷'],['Turkmenistan','🇹🇲'],['Tuvalu','🇹🇻'],['Uganda','🇺🇬'],['Ukraine','🇺🇦'],['United Arab Emirates','🇦🇪'],['United Kingdom','🇬🇧'],['United States','🇺🇸'],['Uruguay','🇺🇾'],['Uzbekistan','🇺🇿'],['Vanuatu','🇻🇺'],['Vatican City','🇻🇦'],['Venezuela','🇻🇪'],['Vietnam','🇻🇳'],['Yemen','🇾🇪'],['Zambia','🇿🇲'],['Zimbabwe','🇿🇼']
].map(([name,flag])=>({name,flag}));
const aliases={usa:'United States',us:'United States',america:'United States',uk:'United Kingdom',britain:'United Kingdom',england:'United Kingdom',uae:'United Arab Emirates',holland:'Netherlands',korea:'South Korea',turkiye:'Turkey','viet nam':'Vietnam','czech republic':'Czechia'};
const scores=new Map(countries.map(c=>[c.name,0])), flags=new Map(countries.map(c=>[c.flag,c])), byName=new Map(countries.map(c=>[c.name.toLowerCase(),c]));
let chatId=null,pageToken=null,pollMs=FALLBACK,status='Waiting for live stream…',seen=new Set(),busy=false;
const snapshot=()=>countries.map(c=>({name:c.name,flag:c.flag,score:scores.get(c.name)||0})).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name));
function send(){const msg=JSON.stringify({type:'state',target:TARGET,status,scores:snapshot()});for(const c of wss.clients)if(c.readyState===1)c.send(msg)}
function detect(text){const t=String(text||'').toLowerCase().trim();for(const [f,c] of flags)if(t.includes(f))return c;const n=t.replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();const exact=byName.get(n)||byName.get(aliases[n]);if(exact)return exact;for(const c of countries){const a=c.name.toLowerCase();if(new RegExp(`(^|\\s)${a.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')}(?=\\s|$)`,'i').test(n))return c}return null}
async function yt(path,params){const u=new URL('https://www.googleapis.com/youtube/v3/'+path);for(const[k,v]of Object.entries({...params,key:KEY}))u.searchParams.set(k,v);const r=await fetch(u);const d=await r.json();if(!r.ok)throw Error(d?.error?.message||`YouTube API ${r.status}`);return d}
async function discover(){if(!KEY||!VIDEO){status='Set YOUTUBE_API_KEY and YOUTUBE_VIDEO_ID in .env';return false}const d=await yt('videos',{part:'liveStreamingDetails',id:VIDEO});const id=d.items?.[0]?.liveStreamingDetails?.activeLiveChatId;if(!id){status='Live chat is not active yet. Start the livestream.';return false}if(id!==chatId){chatId=id;pageToken=null;status='Connected to YouTube Live Chat'}return true}
async function poll(){if(busy)return;busy=true;try{if(!(await discover()))return;const p={liveChatId:chatId,part:'snippet,authorDetails',maxResults:200};if(pageToken)p.pageToken=pageToken;const d=await yt('liveChat/messages',p);pageToken=d.nextPageToken||pageToken;pollMs=Math.max(1000,Number(d.pollingIntervalMillis||FALLBACK));for(const item of d.items||[]){if(seen.has(item.id))continue;seen.add(item.id);const type=item.snippet?.type||'';const text=item.snippet?.displayMessage||item.snippet?.textMessageDetails?.messageText||item.snippet?.superChatDetails?.userComment||'';const c=detect(text);if(c){let points=1;if(type==='superChatEvent')points=SUPERCHAT_POINTS;if(type==='superStickerEvent')points=SUPERSTICKER_POINTS;scores.set(c.name,(scores.get(c.name)||0)+points)}}if(seen.size>6000)seen=new Set([...seen].slice(-3000));send()}catch(e){status='YouTube error: '+e.message;send()}finally{busy=false;setTimeout(poll,pollMs)}}
app.use(express.static('public'));app.get('/api/state',(_,res)=>res.json({target:TARGET,status,scores:snapshot()}));wss.on('connection',ws=>ws.send(JSON.stringify({type:'state',target:TARGET,status,scores:snapshot()})));
server.listen(PORT,()=>{console.log(`http://localhost:${PORT}`);poll()});
