import { writeFileSync, existsSync } from 'node:fs';

// UN member states, plus Vatican, Palestine, Kosovo and Taiwan.
const CODES = `af al dz ad ao ag ar am au at az bs bh bd bb by be bz bj bt bo ba bw br bn bg bf bi
cv kh cm ca cf td cl cn co km cg cd cr ci hr cu cy cz dk dj dm do ec eg sv gq er ee sz et fj fi fr
ga gm ge de gh gr gd gt gn gw gy ht hn hu is in id ir iq ie il it jm jp jo kz ke ki kp kr kw kg la
lv lb ls lr ly li lt lu mg mw my mv ml mt mh mr mu mx fm md mc mn me ma mz mm na nr np nl nz ni ne
ng mk no om pk pw pa pg py pe ph pl pt qa ro ru rw kn lc vc ws sm st sa sn rs sc sl sg sk si sb so
za ss es lk sd sr se ch sy tj tz th tl tg to tt tn tr tm tv ug ua ae gb us uy uz vu ve vn ye zm zw
va ps xk tw`.split(/\s+/).filter(Boolean);

const dupes = CODES.filter((c, i) => CODES.indexOf(c) !== i);
if (dupes.length) throw new Error(`duplicate codes: ${dupes.join(', ')}`);

const names = new Intl.DisplayNames(['en'], { type: 'region' });
const missing = [];
const rows = [];

for (const code of CODES) {
  if (!existsSync(`node_modules/circle-flags/flags/${code}.svg`)) {
    missing.push(code);
    continue;
  }
  // Kosovo and Taiwan have no CLDR region name in every ICU build.
  const fallback = { xk: 'Kosovo', tw: 'Taiwan' }[code];
  const name = names.of(code.toUpperCase()) ?? fallback;
  const resolved = name === code.toUpperCase() ? fallback : name;
  if (!resolved) throw new Error(`no name for ${code}`);
  rows.push({ code, name: resolved });
}

if (missing.length) throw new Error(`no SVG for: ${missing.join(', ')}`);

rows.sort((a, b) => a.code.localeCompare(b.code));

const body = rows.map((r) => `  { code: '${r.code}', name: ${JSON.stringify(r.name)} },`).join('\n');
const out = `/**
 * Every country that enters the arena.
 *
 * Generated by tools/gen-flags — do not hand-edit. Codes are lowercase ISO
 * 3166-1 alpha-2 and match the atlas frame names exactly. Lowercase is enforced
 * rather than conventional: CI is Linux and case-sensitive while macOS is not, so
 * a casing mismatch here is invisible locally and 404s only in production.
 */
export interface FlagEntry {
  readonly code: string;
  readonly name: string;
}

export const FLAGS: readonly FlagEntry[] = [
${body}
];
`;
writeFileSync('src/data/flags.ts', out);
console.log(`wrote ${rows.length} flags`);
